In [13]:
#Import bibliotek
import pandas as pd
from pycaret.regression import *

In [14]:
#Pobranie danych i zapisanie do dataframe
data_frame = pd.read_csv("../data/01_raw/car_prices_small.csv", error_bad_lines=False)
data_frame['saledate'] = pd.to_datetime(data_frame['saledate'], utc=True)
data_frame.dtypes

year                          int64
make                         object
model                        object
trim                         object
body                         object
transmission                 object
vin                          object
state                        object
condition                   float64
odometer                      int64
color                        object
interior                     object
seller                       object
mmr                           int64
sellingprice                  int64
saledate        datetime64[ns, UTC]
dtype: object

In [5]:
data_frame.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639,white,black,"kia motors america, inc",20500,21500,2014-12-16 04:30:00+00:00
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393,white,beige,"kia motors america, inc",20800,21500,2014-12-16 04:30:00+00:00
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,4.5,1331,gray,black,financial services remarketing (lease),31900,30000,2015-01-14 20:30:00+00:00
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,4.1,14282,white,black,volvo na rep/world omni,27500,27750,2015-01-28 20:30:00+00:00
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,4.3,2641,gray,black,financial services remarketing (lease),66000,67000,2014-12-18 04:30:00+00:00

In [6]:
#Lista cech
data_frame.columns

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')

In [7]:
data_frame.shape

(31, 16)

In [8]:
model_setup = setup(data=data_frame, target="sellingprice")

In [9]:
#Porównanie modeli
best_model =compare_models()

In [10]:
#Ewaluacja najlepszego modelu
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [12]:
output_df = predict_model(best_model, data=data_frame)

In [16]:
pipeline, model_path = save_model(best_model, "pycarret_model_1")

Transformation Pipeline and Model Successfully Saved

In [17]:
model_path

'pycarret_model_1.pkl'

In [18]:
pipeline

Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[],
                                      target='sellingprice',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_str...
                ('fix_perfect', Remove_100(target='sellingprice')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model',
                 Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                       max_iter=1000, normalize=False, positive=False,
                       precompute=False, random_state=4452, selection='cyclic',
                       tol=0.0001, warm_start=False)]],
         verbose=False)

In [23]:
plot_model(best_model, plot="pipeline")

ValueError: Plot Not Available. Please see docstring for list of available Plots.

In [22]:
?plot_model